name: GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
            go-version: '1.14.1'
      - name: Checkout
        uses: actions/checkout@master
        with:
            fetch-depth: 1
      - name: Install gournal
        run: |
          GOBIN=$(pwd)/bin go get github.com/matsuyoshi30/gournal
          ./bin/gournal pub
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: shuho.matsuyoshi30.net
